name:                vertex
version:             0.1.0.0
github:              "sano-jin/vertex"
license:             BSD3
author:              "sano"
maintainer:          "sano-jin@akane.waseda.jp"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sano-jin/vertex#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- containers
- extra

library:
  source-dirs: src

executables:
  vertex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vertex

tests:
  vertex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vertex
