block = 
    | line "." block
    | line "."
    | line

line = 
    | list ":-" list
    | list

list =
    | process "," list
    | process

creation =
    | ( \(linkName " ") + "." ) * process    

process =
    | atom              (* start from AtomName *)
    | indirection       (* start from PointerName *)
    | "(" line ")"      (* start from opening parentheses *)

atom =
    | AtomName "("  ")"
    | AtomName "(" linkList ")"
    | AtomName

linkList =
    | pointing_to "," linkList
    | pointing_to

pointing_to = 
    | atom
    | LinkName

indirection =
    | LinkName "->" pointing_to    


(* "." < ":-" < ","  *)
