#!/bin/bash
parse() {
  input="$1"
  echo \""$input"\"
  ./main "$input"
}

parse "a"
parse "a()"
parse "a(b, c)"
parse "a(b, c), d"
parse "d, c, b, a"
parse "d, ((c, b), a)"
parse "a(B, c()), d"
parse "a(B, c(d, E))"
parse "A -> a()"
parse "_A -> a()"
parse "A -> a(B, _C), _C -> g"
parse "A -> a() :- b"
parse "A -> a :- (b :- c)"
parse "A -> a, g :- b. f"
parse "A -> a() :- b. f."
parse "a :- b, c . d ."
parse "a X"
parse "a a"
parse "a a a"
parse "a a a b."
parse "a a a X -> a"
parse "a , (X)"
